import Banner from "@/components/Banner";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function FanLayout({ children }: { children: React.ReactNode }) {
  const data = [
    {
      category: "홈런볼예측",
      url: "/fan/homerun",
      desc: "홈런볼 예측 페이지를 소개합니다.",
    },
    {
      category: "경기예측",
      url: "/fan/",
      desc: "각기 다른 매력을 지닌 kt wiz 팀을 소개합니다.",
    },
    {
      category: "응원게시판",
      url: "/fan/board",
      desc: "각기 다른 매력을 지닌 kt wiz 팀을 소개합니다.",
    },
  ];
  return (
    <div>
      <Banner items={data} />
      {children}
    </div>
  );
}
