import Banner from "../../components/Banner"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function PlayerLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const data = [
    {
      category: "코칭스태프",
      url: "/player/coach",
      desc: "최고의 kt wiz 코칭스텝을 소개합니다.",
    },
    {
      category: "선수단",
      url: "/player/team",
      desc: "각기 다른 매력을 지닌 kt wiz 팀을 소개합니다.",
    },
  ]
  return (
    <>
      <Banner items={data} />
      {children}
    </>
  )
}
