import "./global.css"
import Footer from "../components/Footer"
import Header from "../components/Header"
import Chatbot from "../components/Chatbot";


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <Chatbot />
      </body>
    </html>
  );
}
